### ISSUE TITLE
Does it still work?

### ISSUE THREAD

**Issue by impactcolor** [chrisfinch/svg-to-json#2]
Does this still work?  I'm getting this error:

SyntaxError: Setter must have exactly one formal parameter.
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/ohms/Code/svg-to-json/node_modules/raphael-browserify/node_modules/jsdom/lib/jsdom/level2/core.js:1:94)

**Comment by Developer0924** [comment]
Did you get solution for this? I'm getting same error

**Comment by impactcolor** [comment]
@Developer0924 No didn't get anywhere on it.  I even forgot what I ended up using lol.

**Comment by Developer0924** [comment]
lol, I have fixed it, but now I am getting new error' jsdom.env is not a function' may be jsdom version is too old that is why I am getting it, I am trying to resolve it, let me know if you have any idea on it. Thanks
